---

- name: Add PHP7 repo
  become: yes
  apt_repository:
    repo: ppa:ondrej/php

- name: Install PHP
  become: yes
  apt:
    update_cache: yes
    name: "{{ item }}"
  with_items:
    - apt-utils
    - "{{ sansible_php_version }}"
    - "{{ sansible_php_version }}-common"
    - "{{ sansible_php_version }}-fpm"
    - "{{ sansible_php_version }}-cli"
  when: sansible_php_install_base_packages == true

- name: Install base PHP modules
  become: yes
  apt:
    name: "{{ item }}"
  with_items: "{{ sansible_php_modules }}"

- name: Install extra PHP packages
  become: yes
  apt:
    name: "{{ item }}"
  with_items: "{{ sansible_php_extras }}"

- name: Install PECL modules
  include: pecl.yml
  when: sansible_php_pecl != []

- name: Install custom FPM service
  include: fpm.yml
  when: sansible_php_fpm_user is not none
