---

driver:
  name: docker

platforms:
  - name: sansible_php-7-xenial
    image: solita/ubuntu-systemd:xenial
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: sansible_php-7-bionic
    image: solita/ubuntu-systemd:bionic
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  lint:
    name: ansible-lint

lint:
  name: yamllint
  options:
    config-data:
      extends: default
      ignore: .venv_ansible*
      rules:
        line-length:
          max: 159
        truthy: disable

dependency:
  name: galaxy
  options:
    role-file: requirements.yml

scenario:
  name: php7

verifier:
  name: testinfra
  lint:
    name: flake8
